### ISSUE TITLE
Can't install using minimal installation command line

### ISSUE THREAD

**Issue by LunaticLeo** [allen-ball/ganymede-kernel#2]
Hi, Allen. 

When I'm using the minimal installation command line, there are some problems happen.  Sorry for the request, but I'm a beginner using java, and my system is windows10. After searching on google, I still can't find a reason why it's not worked. Does it mean I have to install spring or maven first?

![Capture](https://user-images.githubusercontent.com/23627067/135968642-8af760cf-9655-486a-8ec1-1ad374f3da7e.PNG)
![Capture](https://user-images.githubusercontent.com/23627067/135968678-bd54f97d-169b-45eb-a0cd-c845f52679fa.PNG)

Thanks for your time and consideration!

**Comment by allen-ball** [comment]
The install code is assuming a UNIX-like environment and failing while locating the Java and Python executables and environments.

**Comment by LunaticLeo** [comment]
So what can I do to use this kernel successfully in win10? Should I recompile a new jar on windows?

**Comment by patelabhilash** [comment]
> So what can I do to use this kernel successfully in win10? Should I recompile a new jar on windows?

refer this:
https://github.com/allen-ball/ganymede/issues/9#issuecomment-1630704458

currently no support for windows. Work around is to install WSL in windows and run from there.

**Comment by NikkU0** [comment]
I am trying to install on VM and getting this weird error. 
Line 117 is  
`var sys_prefix_dir = getOutputAsString(python, "-c", "import sys; print(sys.prefix)");`
how come it is running /bin/sh.
 [/bin/sh, -c, import sys; print(sys.prefix)]


`java -jar ganymede-2.1.2.20230910.jar -i
ERROR [    main] Install                                  : Cannot read output of [/bin/sh, -c, import sys; print(sys.prefix)]
java.io.IOException: Cannot read output of [/bin/sh, -c, import sys; print(sys.prefix)]
	at ganymede.install.Install.getOutputAsString(Install.java:296)
	at ganymede.install.Install.run(Install.java:177)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
	at ganymede.Launcher.run(Launcher.java:92)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
`
